### ISSUE TITLE
[Todo] Progress bar at the top of the screen

### ISSUE THREAD

**Issue by anthonygedeon** [anthonygedeon/watch-anime#21]
- [ ] When data is still loading, it should increase in width by 10

- [ ] When progress reaches 100% it should disappear with smooth transition

- [ ] During loading, progress bar should transition whenever width get's increased
